apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: white-rabbit
  labels:
    app: postgresql
    group: white-rabbit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
