apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: white-rabbit
  labels:
    app: postgresql
    group: white-rabbit
spec:
  selector:
    app: postgresql
    group: white-rabbit
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
