apiVersion: v1
kind: Service
metadata:
  name: kubeview
  namespace: tools
  labels:
    app: kubeview
    group: tools
  # annotations:
    # !CHANGE THIS! To your real DNS domain
    # external-dns.alpha.kubernetes.io/hostname: kubeview.f0dfafed36164c7faac0.westeurope.aksapp.io
    # kubernetes.io/ingress.class: addon-http-application-routing
spec:
  selector:
    app: kubeview
    group: tools
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
