apiVersion: v1
kind: Service
metadata:
  name: server-app
  namespace: white-rabbit
  labels:
    app: server-app
    group: white-rabbit
spec:
  selector:
    app: server-app
    group: white-rabbit
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-metrics
      port: 8090
      targetPort: 8090
      protocol: TCP
