apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server-app
  namespace: white-rabbit
  labels:
    app: server-app
    group: white-rabbit
    prometheus: k8s
spec:
  selector:
    matchLabels:
      app: server-app
      group: white-rabbit
  namespaceSelector:
    matchNames:
      - white-rabbit
  endpoints:
    - port: http-metrics
      path: /actuator/prometheus
      interval: 10s
      scrapeTimeout: 9s
