apiVersion: v1
kind: Service
metadata:
  name: client-app
  namespace: white-rabbit
  labels:
    app: client-app
    group: white-rabbit
spec:
  type: NodePort
  selector:
    app: client-app
    group: white-rabbit
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: http-metrics
      port: 8090
      targetPort: 8090
      protocol: TCP
