apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: black-sheep
  labels:
    app: postgresql
    group: black-sheep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
