apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: black-sheep
  labels:
    app: postgresql
    group: black-sheep
spec:
  selector:
    app: postgresql
    group: black-sheep
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
