apiVersion: v1
kind: ConfigMap
metadata:
  name: client-app
  namespace: black-sheep
  labels:
    app: client-app
    group: black-sheep
data:
  SPRING_PROFILES_ACTIVE: kube
  HEAP_SIZE: 256m
  META_SIZE: 300m
  SERVER_HOST: server-app
  SERVER_PORT: "8080"
