apiVersion: v1
kind: Service
metadata:
  name: client-app
  namespace: black-sheep
  labels:
    app: client-app
    group: black-sheep
spec:
  type: NodePort
  selector:
    app: client-app
    group: black-sheep
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
