apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app
  namespace: black-sheep
  labels:
    app: server-app
    group: black-sheep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: server-app
      group: black-sheep
  template:
    metadata:
      labels:
        app: server-app
        group: black-sheep
    spec:
      restartPolicy: Always
      containers:
        - name: server-app
          image: black-sheep/server-app:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: server-app
            - secretRef:
                name: server-app
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 750m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /users
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /users
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      terminationGracePeriodSeconds: 30
