apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels:
    k8s-app: apiserver
spec:
  jobLabel: component
  endpoints:
  - port: https
    interval: 30s
    scheme: https
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      serverName: kubernetes
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    # metricRelabelings:
    # - action: drop
    #   regex: etcd_(debugging|disk|request|server).*
    #   sourceLabels:
    #   - __name__
    # - action: drop
    #   regex: apiserver_admission_controller_admission_latencies_seconds_.*
    #   sourceLabels:
    #   - __name__
    # - action: drop
    #   regex: apiserver_admission_step_admission_latencies_seconds_.*
    #   sourceLabels:
    #   - __name__
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      component: apiserver
      provider: kubernetes
